import ERC20 from '../abis/tokens/DAI.js';
import CHAI from '../abis/chai/CHAI.json';
import cToken from '../abis/compound/cDAI';
import aToken from '../abis/aave/AToken.json';
import yToken from '../abis/dydx/yToken.json';
import iToken from '../abis/fulcrum/iToken.json';
import IdleTokenV3 from '../contracts/IdleTokenV3.json';
import IdleTokenV4 from '../contracts/IdleTokenV4.json';
import IdleConverterPersonalSignV4 from '../contracts/IdleConverterPersonalSignV4.json';

const availableTokens = {
  42:{
    best:{
      DAI:{
        token:'DAI',
        decimals:18,
        enabled:true,
        abi:ERC20.abi,
        govTokensDisabled:false,
        color:'hsl(40, 95%, 59%)',
        address:'0x4f96fe3b7a6cf9725f59d353f723c1bdb64ca6aa',
        deposit:{
          minAmountForMint:10000,
        },
        wyre:{
          destCurrency:'DAI'
        },
        ramp:{
          swapAsset:'DAI'
        },
        defiPrime:{
          token:'dai'
        },
        idle:{
          abi:IdleTokenV4,
          token:'idleDAIYield',
          address:'0x295CA5bC5153698162dDbcE5dF50E436a58BA21e',
        },
        protocols:[
          {
            name:'compound',
            enabled:true,
            abi:cToken.abi,
            address:'0xf0d0eb522cfa50b716b3b1604c4f0fa6f04376ad',
            token:'cDAI',
            decimals:28,
            functions:{
              exchangeRate:{
                name:'exchangeRateStored',
                params:[]
              }
            },
          }
        ]
      },
    },
    risk:{

    }
  },
  1:{ // Mainnet
    best:{
      DAI:{
        token:'DAI',
        decimals:18,
        enabled:true,
        abi:ERC20.abi,
        govTokensDisabled:false,
        color:'hsl(40, 95%, 59%)',
        address:'0x6b175474e89094c44da98b954eedeac495271d0f',
        deposit:{
          minAmountForMint:10000,
        },
        wyre:{
          destCurrency:'DAI'
        },
        ramp:{
          swapAsset:'DAI'
        },
        defiPrime:{
          token:'dai'
        },
        idle:{
          abi:IdleTokenV4,
          token:'idleDAIYield',
          address:'0x3fe7940616e5bc47b0775a0dccf6237893353bb4',
        },
        migration:{
          enabled:true,
          message:'Idle now supports yield farming and governance tokens distribution. Migrate now your DAI with just one click!',
          oldContract:{
            abi:IdleTokenV3,
            token:'idleDAI',
            name:'idleDAIYieldV3',
            address:'0x78751b12da02728f467a44eac40f5cbc16bd7934',
          },
          oldProtocols:[
            {
              name:'dydx',
              enabled:true,
              abi:yToken,
              address:'0xf424b10e1e9691ae5fb530fe4c3e6b9971013d49',
              token:'yxDAIOld',
              decimals:18,
              functions:{
                exchangeRate:{
                  name:'price',
                  params:[]
                }
              }
            }
          ],
          migrationContract:{
            token:'idleDAI',
            abi:IdleConverterPersonalSignV4,
            name:'IdleConverterV4',
            address:'0xa55caa40b32a02becfad1d0d29c4f1cf38c4c743',
            oldAddresses:[],
            functions:[
              {
                label:'Migrate',
                name:'migrateFromToIdle'
              },
            ]
          }
        },
        protocols:[
          {
            enabled:true,
            abi:cToken.abi,
            name:'compound',
            address:'0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643',
            token:'cDAI',
            decimals:28,
            functions:{
              exchangeRate:{
                name:'exchangeRateStored',
                params:[]
              }
            },
          },
          {
            abi:iToken,
            enabled:true,
            name:'fulcrum',
            address:'0x493c57c4763932315a328269e1adad09653b9081',
            token:'iDAI',
            decimals:18,
            functions:{
              exchangeRate:{
                name:'tokenPrice',
                params:[]
              }
            },
          },
          {
            abi:aToken,
            name:'aave',
            enabled:true,
            address:'0xfC1E690f61EFd961294b3e1Ce3313fBD8aa4f85d',
            token:'aDAI',
            decimals:18,
            functions:{

            }
          },
          {
            abi:CHAI,
            name:'dsr',
            enabled:true,
            address:'0x06AF07097C9Eeb7fD685c692751D5C66dB49c215',
            token:'CHAI',
            decimals:18,
            functions:{

            }
          },
          {
            abi:yToken,
            name:'dydx',
            enabled:true,
            address:'0xb299BCDF056d17Bd1A46185eCA8bCE458B00DC4a',
            token:'yxDAI',
            decimals:18,
            functions:{
              exchangeRate:{
                name:'price',
                params:[]
              }
            }
          }
        ]
      },
      USDC:{
        decimals:6,
        token:'USDC',
        enabled:true,
        abi:ERC20.abi,
        govTokensDisabled:false,
        color:'hsl(211, 67%, 47%)',
        address:'0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
        deposit:{
          minAmountForMint:10000,
        },
        wyre:{
          destCurrency:'USDC'
        },
        defiPrime:{
          token:'usdc'
        },
        idle:{
          abi:IdleTokenV4,
          token:'idleUSDCYield',
          address:'0x5274891bEC421B39D23760c04A6755eCB444797C',
        },
        migration:{
          enabled:true,
          message:'Idle now supports yield farming and governance tokens distribution. Migrate now your USDC with just one click!',
          oldContract:{
            abi:IdleTokenV3,
            token:'idleUSDC',
            name:'idleUSDCYieldV3',
            address:'0x12B98C621E8754Ae70d0fDbBC73D6208bC3e3cA6'
          },
          oldProtocols:[
            {
              abi:yToken,
              name:'dydx',
              enabled:true,
              address:'0x0d81b042bb9939b4d32cdf7861774c442a2685ce',
              token:'yxUSDCOld',
              decimals:18,
              functions:{
                exchangeRate:{
                  name:'price',
                  params:[]
                }
              }
            }
          ],
          migrationContract:{
            abi:IdleConverterPersonalSignV4,
            token:'idleUSDC',
            name:'IdleConverterV4',
            address:'0xa55caa40b32a02becfad1d0d29c4f1cf38c4c743',
            oldAddresses:[],
            functions:[
              {
                label:'Migrate',
                name:'migrateFromToIdle'
              },
            ]
          }
        },
        protocols:[
          {
            name:'compound',
            enabled:true,
            abi:cToken.abi,
            address:'0x39aa39c021dfbae8fac545936693ac917d5e7563',
            token:'cUSDC',
            decimals:16,
            functions:{
              exchangeRate:{
                name:'exchangeRateStored',
                params:[]
              }
            },
          },
          {
            name:'fulcrum',
            enabled:true,
            abi:iToken,
            address:'0xf013406a0b1d544238083df0b93ad0d2cbe0f65f',
            token:'iUSDC',
            decimals:18,
            functions:{
              exchangeRate:{
                name:'tokenPrice',
                params:[]
              }
            },
          },
          {
            name:'aave',
            enabled:true,
            abi:aToken,
            address:'0x9bA00D6856a4eDF4665BcA2C2309936572473B7E',
            token:'aUSDC',
            decimals:18,
            functions:{
              
            }
          },
          {
            name:'dydx',
            enabled:true,
            abi:yToken,
            address:'0xd2F45883627f26EC34825486ca4c25235A0da0C3',
            token:'yxUSDC',
            decimals:18,
            functions:{
              exchangeRate:{
                name:'price',
                params:[]
              }
            }
          }
        ]
      },
      USDT:{
        decimals:6,
        token:'USDT',
        enabled:true,
        abi:ERC20.abi,
        govTokensDisabled:false,
        color:'hsl(211, 67%, 47%)',
        address:'0xdac17f958d2ee523a2206206994597c13d831ec7',
        wyre:{
          destCurrency:'USDT'
        },
        defiPrime:{
          token:'usdt'
        },
        idle:{
          abi:IdleTokenV4,
          token:'idleUSDTYield',
          address:'0xF34842d05A1c888Ca02769A633DF37177415C2f8',
        },
        migration:{
          enabled:true,
          message:'Idle now supports yield farming and governance tokens distribution. Migrate now your USDT with just one click!',
          oldContract:{
            abi:IdleTokenV3,
            token:'idleUSDT',
            name:'idleUSDTYieldV3',
            address:'0x63D27B3DA94A9E871222CB0A32232674B02D2f2D'
          },
          migrationContract:{
            abi:IdleConverterPersonalSignV4,
            token:'idleUSDT',
            name:'IdleConverterV4',
            address:'0xa55caa40b32a02becfad1d0d29c4f1cf38c4c743',
            oldAddresses:[],
            functions:[
              {
                label:'Migrate',
                name:'migrateFromToIdle'
              },
            ]
          }
        },
        protocols:[
          {
            name:'compound',
            enabled:true,
            abi:cToken.abi,
            address:'0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9',
            token:'cUSDT',
            decimals:16,
            functions:{
              exchangeRate:{
                name:'exchangeRateStored',
                params:[]
              }
            },
          },
          {
            name:'fulcrum',
            enabled:true,
            abi:iToken,
            address:'0x8326645f3aa6de6420102fdb7da9e3a91855045b',
            token:'iUSDT',
            decimals:18,
            functions:{
              exchangeRate:{
                name:'tokenPrice',
                params:[]
              }
            },
          },
          {
            name:'aave',
            enabled:true,
            abi:aToken,
            address:'0x71fc860F7D3A592A4a98740e39dB31d25db65ae8',
            token:'aUSDT',
            decimals:18,
            functions:{
              
            }
          }
        ]
      },
      SUSD:{
        decimals:18,
        token:'SUSD',
        enabled:true,
        abi:ERC20.abi,
        govTokensDisabled:false,
        skipMintForDeposit:false,
        color:'hsl(250, 31%, 15%)',
        // icon:'images/tokens/SUSD.svg',
        address:'0x57ab1ec28d129707052df4df418d58a2d46d5f51',
        wyre:{
          destCurrency:'SUSD'
        },
        defiPrime:{
          token:'susd'
        },
        idle:{
          abi:IdleTokenV4,
          token:'idleSUSDYield',
          address:'0xf52cdcd458bf455aed77751743180ec4a595fd3f',
        },
        migration:{
          enabled:true,
          message:'Idle now supports yield farming and governance tokens distribution. Migrate now your SUSD with just one click!',
          oldContract:{
            abi:IdleTokenV3,
            token:'idleSUSD',
            name:'idleSUSDYieldV3',
            address:'0xe79e177d2a5c7085027d7c64c8f271c81430fc9b',
          },
          migrationContract:{
            abi:IdleConverterPersonalSignV4,
            token:'idleSUSD',
            name:'IdleConverterV4',
            address:'0xa55caa40b32a02becfad1d0d29c4f1cf38c4c743',
            oldAddresses:[],
            functions:[
              {
                label:'Migrate',
                name:'migrateFromToIdle'
              },
            ]
          }
        },
        protocols:[
          {
            name:'aave',
            enabled:true,
            abi:aToken,
            address:'0x625aE63000f46200499120B906716420bd059240',
            token:'aSUSD',
            decimals:18,
            functions:{
              
            }
          }
        ]
      },
      TUSD:{
        decimals:18,
        token:'TUSD',
        enabled:true,
        abi:ERC20.abi,
        govTokensDisabled:false,
        skipMintForDeposit:false,
        color:'hsl(217, 100%, 20%)',
        address:'0x0000000000085d4780b73119b644ae5ecd22b376',
        wyre:{
          destCurrency:'TUSD'
        },
        defiPrime:{
          token:'tusd'
        },
        idle:{
          abi:IdleTokenV4,
          token:'idleTUSDYield',
          address:'0xc278041fDD8249FE4c1Aad1193876857EEa3D68c',
        },
        migration:{
          enabled:true,
          message:'Idle now supports yield farming and governance tokens distribution. Migrate now your TUSD with just one click!',
          oldContract:{
            abi:IdleTokenV3,
            token:'idleTUSD',
            name:'idleTUSDYieldV3',
            address:'0x51C77689A9c2e8cCBEcD4eC9770a1fA5fA83EeF1',
          },
          migrationContract:{
            abi:IdleConverterPersonalSignV4,
            token:'idleTUSD',
            name:'IdleConverterV4',
            address:'0xa55caa40b32a02becfad1d0d29c4f1cf38c4c743',
            oldAddresses:[],
            functions:[
              {
                label:'Migrate',
                name:'migrateFromToIdle'
              },
            ]
          }
        },
        protocols:[
          {
            name:'aave',
            enabled:true,
            abi:aToken,
            address:'0x4da9b813057d04baef4e5800e36083717b4a0341',
            token:'aTUSD',
            decimals:18,
            functions:{
              
            }
          }
        ]
      },
      WBTC:{
        decimals:8,
        token:'WBTC',
        enabled:true,
        abi:ERC20.abi,
        govTokensDisabled:false,
        color:'hsl(29, 81%, 59%)',
        address:'0x2260fac5e5542a773aa44fbcfedf7c193bc2c599',
        deposit:{
          minAmountForMint:5000,
        },
        wyre:{
          destCurrency:'WBTC'
        },
        defiPrime:{
          token:'wbtc'
        },
        idle:{
          abi:IdleTokenV4,
          token:'idleWBTCYield',
          address:'0x8C81121B15197fA0eEaEE1DC75533419DcfD3151',
        },
        migration:{
          enabled:true,
          message:'Idle now supports yield farming and governance tokens distribution. Migrate now your WBTC with just one click!',
          oldContract:{
            abi:IdleTokenV3,
            token:'idleWBTC',
            name:'idleWBTCYieldV3',
            address:'0xD6f279B7ccBCD70F8be439d25B9Df93AEb60eC55'
          },
          migrationContract:{
            abi:IdleConverterPersonalSignV4,
            token:'idleWBTC',
            name:'IdleConverterV4',
            address:'0xa55caa40b32a02becfad1d0d29c4f1cf38c4c743',
            oldAddresses:[],
            functions:[
              {
                label:'Migrate',
                name:'migrateFromToIdle'
              },
            ]
          }
        },
        protocols:[
          {
            name:'compound',
            enabled:true,
            abi:cToken.abi,
            address:'0xc11b1268c1a384e55c48c2391d8d480264a3a7f4',
            token:'cWBTC',
            decimals:18,
            functions:{
              exchangeRate:{
                name:'exchangeRateStored',
                params:[]
              }
            },
          },
          {
            abi:iToken,
            decimals:18,
            token:'iWBTC',
            enabled:true,
            name:'fulcrum',
            address:'0xba9262578efef8b3aff7f60cd629d6cc8859c8b5',
            functions:{
              exchangeRate:{
                name:'tokenPrice',
                params:[]
              }
            },
          },
          {
            name:'aave',
            enabled:true,
            abi:aToken,
            address:'0xfc4b8ed459e00e5400be803a9bb3954234fd50e3',
            token:'aWBTC',
            decimals:18,
            functions:{
              
            }
          }
        ]
      }
    },
    risk:{
      DAI:{
        decimals:18,
        token:'DAI',
        enabled:true,
        abi:ERC20.abi,
        govTokensDisabled:false,
        color:'hsl(40, 95%, 59%)',
        address:'0x6b175474e89094c44da98b954eedeac495271d0f',
        wyre:{
          destCurrency:'DAI'
        },
        ramp:{
          swapAsset:'DAI'
        },
        defiPrime:{
          token:'dai'
        },
        idle:{
          abi:IdleTokenV4,
          token:'idleDAISafe',
          address:'0xa14ea0e11121e6e951e87c66afe460a00bcd6a16'
        },
        migration:{
          enabled:true,
          oldContract:{
            abi:IdleTokenV3,
            token:'idleDAI',
            name:'idleDAISafeV3',
            address:'0x1846bdfDB6A0f5c473dEc610144513bd071999fB'
          },
          oldProtocols:[
            {
              name:'dydx',
              enabled:true,
              abi:yToken,
              address:'0xf424b10e1e9691ae5fb530fe4c3e6b9971013d49',
              token:'yxDAIOld',
              decimals:18,
              functions:{
                exchangeRate:{
                  name:'price',
                  params:[]
                }
              }
            }
          ],
          migrationContract:{
            abi:IdleConverterPersonalSignV4,
            token:'idleDAI',
            name:'IdleConverterV4',
            address:'0xa55caa40b32a02becfad1d0d29c4f1cf38c4c743',
            oldAddresses:[],
            functions:[
              {
                label:'Migrate',
                name:'migrateFromToIdle'
              },
            ]
          }
        },
        protocols:[
          {
            name:'compound',
            enabled:true,
            abi:cToken.abi,
            address:'0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643',
            token:'cDAI',
            decimals:28,
            functions:{
              exchangeRate:{
                name:'exchangeRateStored',
                params:[]
              }
            },
          },
          {
            name:'fulcrum',
            enabled:true,
            abi:iToken,
            address:'0x493c57c4763932315a328269e1adad09653b9081',
            token:'iDAI',
            decimals:18,
            functions:{
              exchangeRate:{
                name:'tokenPrice',
                params:[]
              }
            },
          },
          {
            name:'aave',
            enabled:true,
            abi:aToken,
            address:'0xfC1E690f61EFd961294b3e1Ce3313fBD8aa4f85d',
            token:'aDAI',
            decimals:18,
            functions:{

            }
          },
          {
            name:'dsr',
            enabled:true,
            abi:CHAI,
            address:'0x06AF07097C9Eeb7fD685c692751D5C66dB49c215',
            token:'CHAI',
            decimals:18,
            functions:{

            }
          },
          {
            name:'dydx',
            enabled:true,
            abi:yToken,
            address:'0xb299BCDF056d17Bd1A46185eCA8bCE458B00DC4a',
            token:'yxDAI',
            decimals:18,
            functions:{
              exchangeRate:{
                name:'price',
                params:[]
              }
            }
          }
        ]
      },
      USDC:{
        decimals:6,
        token:'USDC',
        enabled:true,
        abi:ERC20.abi,
        govTokensDisabled:false,
        color:'hsl(211, 67%, 47%)',
        address:'0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
        deposit:{
          minAmountForMint:10000,
        },
        wyre:{
          destCurrency:'USDC'
        },
        defiPrime:{
          token:'usdc'
        },
        idle:{
          abi:IdleTokenV4,
          token:'idleUSDCSafe',
          address:'0x3391bc034f2935ef0e1e41619445f998b2680d35'
        },
        migration:{
          enabled:true,
          oldContract:{
            abi:IdleTokenV3,
            token:'idleUSDC',
            name:'idleUSDCSafeV3',
            address:'0xcDdB1Bceb7a1979C6caa0229820707429dd3Ec6C',
          },
          oldProtocols:[
            {
              name:'dydx',
              enabled:true,
              abi:yToken,
              address:'0x0d81b042bb9939b4d32cdf7861774c442a2685ce',
              token:'yxUSDCOld',
              decimals:18,
              functions:{
                exchangeRate:{
                  name:'price',
                  params:[]
                }
              }
            }
          ],
          migrationContract:{
            abi:IdleConverterPersonalSignV4,
            token:'idleUSDC',
            name:'IdleConverterV4',
            address:'0xa55caa40b32a02becfad1d0d29c4f1cf38c4c743',
            oldAddresses:[],
            functions:[
              {
                label:'Migrate',
                name:'migrateFromToIdle'
              },
            ]
          }
        },
        protocols:[
          {
            name:'compound',
            enabled:true,
            abi:cToken.abi,
            address:'0x39aa39c021dfbae8fac545936693ac917d5e7563',
            token:'cUSDC',
            decimals:16,
            functions:{
              exchangeRate:{
                name:'exchangeRateStored',
                params:[]
              }
            },
          },
          {
            name:'fulcrum',
            enabled:true,
            abi:iToken,
            address:'0xf013406a0b1d544238083df0b93ad0d2cbe0f65f',
            token:'iUSDC',
            decimals:18,
            functions:{
              exchangeRate:{
                name:'tokenPrice',
                params:[]
              }
            },
          },
          {
            name:'aave',
            enabled:true,
            abi:aToken,
            address:'0x9bA00D6856a4eDF4665BcA2C2309936572473B7E',
            token:'aUSDC',
            decimals:18,
            functions:{
              
            }
          },
          {
            name:'dydx',
            enabled:true,
            abi:yToken,
            address:'0xd2F45883627f26EC34825486ca4c25235A0da0C3',
            token:'yxUSDC',
            decimals:18,
            functions:{
              exchangeRate:{
                name:'price',
                params:[]
              }
            }
          }
        ]
      },
      USDT:{
        decimals:6,
        token:'USDT',
        enabled:true,
        abi:ERC20.abi,
        govTokensDisabled:false,
        color:'hsl(211, 67%, 47%)',
        address:'0xdac17f958d2ee523a2206206994597c13d831ec7',
        wyre:{
          destCurrency:'USDT'
        },
        defiPrime:{
          token:'usdt'
        },
        idle:{
          abi:IdleTokenV4,
          token:'idleUSDTSafe',
          address:'0x28fAc5334C9f7262b3A3Fe707e250E01053e07b5'
        },
        migration:{
          enabled:true,
          oldContract:{
            abi:IdleTokenV3,
            token:'idleUSDT',
            name:'idleUSDTSafeV3',
            address:'0x42740698959761baf1b06baa51efbd88cb1d862b'
          },
          migrationContract:{
            abi:IdleConverterPersonalSignV4,
            token:'idleDAI',
            name:'IdleConverterV4',
            address:'0xa55caa40b32a02becfad1d0d29c4f1cf38c4c743',
            oldAddresses:[],
            functions:[
              {
                label:'Migrate',
                name:'migrateFromToIdle'
              },
            ]
          }
        },
        protocols:[
          {
            name:'compound',
            enabled:true,
            abi:cToken.abi,
            address:'0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9',
            token:'cUSDT',
            decimals:16,
            functions:{
              exchangeRate:{
                name:'exchangeRateStored',
                params:[]
              }
            },
          },
          {
            name:'fulcrum',
            enabled:true,
            abi:iToken,
            address:'0x8326645f3aa6de6420102fdb7da9e3a91855045b',
            token:'iUSDT',
            decimals:18,
            functions:{
              exchangeRate:{
                name:'tokenPrice',
                params:[]
              }
            },
          },
          {
            name:'aave',
            enabled:true,
            abi:aToken,
            address:'0x71fc860F7D3A592A4a98740e39dB31d25db65ae8',
            token:'aUSDT',
            decimals:18,
            functions:{
              
            }
          }
        ]
      }
    }
  }
};

export default availableTokens;